### ISSUE TITLE
Python Compatibility issues

### ISSUE THREAD

**Issue by sworisbreathing** [2bndy5/CircuitPython-mocks#17]
I found this project a couple hours ago and tried to get it going on a new project on my BeagleBone Black, which is running the latest IoT firmware (Debian 11). On that device, the system-installed python is 3.9.

circuitpython_mocks has a couple compatibility issues that I've found so far:

1. [`typing.Self`](https://docs.python.org/3/library/typing.html#typing.Self) imported in `_mixins.py` was introduced in Python 3.11. In earlier versions of python, it needs to be imported from the backport package `typing_extensions` rather than `typing`
2. `operations.py` uses union types, which were introduced in Python 3.10

I'm mostly raising this because the project homepage and `pyproject.toml` claim compatibility with Python versions going back to 3.7, and I don't believe that's the case here, but I do believe it's doable.

**Comment by 2bndy5** [comment]
# :man_facepalming:
I wrote this lib inside a day. I forgot to check older python versions for compatibility.
