### ISSUE TITLE
implement mocks for `board.SPI` and `board.I2C` classes 

### ISSUE THREAD

**Issue by 2bndy5** [2bndy5/CircuitPython-mocks#5]
I forgot to implement this before first release. It should be added.

FYI, `board.SPI` and `board.I2C` is not available for all CircuitPython boards, so I think its generally discouraged to use them despite their convenience...

**Comment by EAGrahamJr** [comment]
A lot of the newer boards also have the `board.STEMMA_I2C()` port.

**Comment by 2bndy5** [comment]
Really? Does it instantiate a `busio.I2C` object? I can add that to the open PR, thanks.

**Comment by 2bndy5** [comment]
Are there also special/alias pins for the stemma port as well (like `board.STEMMA_SDA`)?

**Comment by 2bndy5** [comment]
I'm seeing `SDA1` and `SCL1` on my qypt rp2040 board:
```python
Adafruit CircuitPython 9.1.1 on 2024-07-22; Adafruit QT Py RP2040 with rp2040
>>> import board
>>> dir(board)
['__class__', '__name__', 'A0', 'A1', 'A2', 'A3', 'BUTTON', 'D0', 'D1', 'D10', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'I2C', 'MISO', 'MOSI', 'NEOPIXEL', 'NEOPIXEL_POWER', 'RX', 'SCK', 'SCL', 'SCL1', 'SDA', 'SDA1', 'SPI', 'STEMMA_I2C', 'TX', 'UART', '__dict__', 'board_id']

**Comment by EAGrahamJr** [comment]
&ou might want to check but, iirc 'STEMMA_I2C' is an "alias" for the (SDA1/SCL1) ports.

**Comment by 2bndy5** [comment]
`board.STEMMA_I2C()` is not in the CirPy documentation, but it would make sense if that's the case. Its probably better (in this mock lib context) for `STEMMA_I2C()` to instantiate `I2C(SCL1, SDA1)` instead of a primary bus. Not all boards would treat the stemma connector as a separate bus, but then again not all boards might have a secondary I2C bus available (and may still provide a `board.STEMMA_I2C()`).

I'm coding this as we speak, but I'm currently hung up on the fact that these `board.***()` functions provide singleton instances. This would definitely be applicable to a mock context because the instantiated mock objects have a instance attribute called `expectations` (deque) that should be persistent in singletons.
